[package]
name = "snake"
version = "0.1.0"
authors = ["Mitchell Valine <mitchell.valine@mirumagency.com>"]

[[bin]]
name = "snake"

[dependencies]
piston = "0.32.0" 
piston_window = "0.67.0"
piston2d-graphics = "0.21.1"
pistoncore-glutin_window = "0.37.0"
piston2d-opengl_graphics = "0.44.0"
